### ISSUE TITLE
token key invalidating session and clearing localStorage

### ISSUE THREAD

**Issue by JFickel** [simplabs/ember-cli-simple-auth-devise#12]
In this guide 
https://github.com/simplabs/ember-simple-auth/tree/master/packages/ember-simple-auth-devise
you have the server return data with a token key.
```ruby
 data = {
          token:      self.resource.authentication_token,
          user_email: self.resource.email
        }
```
I also see a commit "change devise user_token to token".
https://github.com/simplabs/ember-simple-auth/commit/e146cb584227b27e56c4dd987a03a8149051905e

When I use token as my key, the session doesn't persist during page reload because localStorage is cleared. 

```javascript
JSON.parse(localStorage['ember_simple_auth:session'])
Object {authenticator: "simple-auth-authenticator:devise", token: "bHbziDNfiM64hP_HqgPj", user_email: "example@example.com"}
```

I found this: http://stackoverflow.com/questions/25215010/ember-simple-auth-session-lost-on-refresh

When I change the data key to user_token in rails, the session persists. Not sure if I missed something.

**Comment by JFickel** [comment]
Ah, it looks like that commit is on master. I'm using version 0.7.2.

I think I'll just change the tokenAttributeName for now.

```javascript
ENV['simple-auth-devise'] = {
  tokenAttributeName: 'token'
}
```

**Comment by marcoow** [comment]
Yeah, that's fixed but not released yet - will release week.
