### ISSUE TITLE
ember-cli 0.2.0 compatibility

### ISSUE THREAD

**Issue by john-griffin** [simplabs/ember-cli-simple-auth-devise#13]
When installing the addon into a fresh ember-cli `0.2.0-beta.1` project the browser throws the following error:

`Uncaught Error: Could not find module simple-auth/utils/load-config`

Still looking into the exact cause.

**Comment by marcoow** [comment]
Can you check the bower package is actually installed?

**Comment by john-griffin** [comment]
`ls bower_components/ember-simple-auth`
```
LICENSE                         simple-auth-oauth2.js
README.md                       simple-auth-testing.amd.js
bower.json                      simple-auth-testing.js
simple-auth-cookie-store.amd.js simple-auth-torii.amd.js
simple-auth-cookie-store.js     simple-auth-torii.js
simple-auth-devise.amd.js       simple-auth.amd.js
simple-auth-devise.js           simple-auth.js
simple-auth-oauth2.amd.js
```

**Comment by john-griffin** [comment]
I get the same error with a fresh install of `ember-cli-simple-auth-oauth2`

**Comment by marcoow** [comment]
Hm, looks like ember-cli 0.2.0 will introduce some [changes to the way addons are handled](https://github.com/ember-cli/ember-cli/releases) - might very well be related to that.

**Comment by Dragsbaek** [comment]
Any updates to this?

**Comment by marcoow** [comment]
@john-griffin: did you find out why it's failing?

**Comment by john-griffin** [comment]
I'm not able to return to this until Wednesday. I believe it's due to the way the addons are packaged but did not have chance to get to the bottom of it. Try asking on the #ember-cli IRC channel, they are quite helpful.

**Comment by ballPointPenguin** [comment]
I was seeing this problem on ember-cli 0.2.0-beta as well.

It seems to have vanished after a fresh
    ember install:addon ember-cli-simple-auth
    ember install:addon ember-cli-simple-auth-devise

hope that helps

**Comment by john-griffin** [comment]
Yeah that works for me. Seem like the base simple-auth addon needs to be installed separately now. I'll update the docs.

**Comment by esbanarango** [comment]
:+1:

**Comment by marcoow** [comment]
I'm not actually sure what the problem is here - probably just some change in ember-cli that I'm missing though. I opened an issue to clarify that: https://github.com/ember-cli/ember-cli/issues/3531

**Comment by marcoow** [comment]
Docs where updated as @john-griffin suggested - unfortunately there's no better fix for now.
