### ISSUE TITLE
Install instructions do not work

### ISSUE THREAD

**Issue by hollow** [simplabs/ember-cli-simple-auth-devise#15]
$ ember install ember-cli-simple-auth
version: 0.2.3
Could not find watchman, falling back to NodeWatcher for file system events.
Visit http://www.ember-cli.com/#watchman for more info.
Installed packages for tooling via npm.
installing
Installing browser packages via Bower...
  cached git://github.com/simplabs/ember-simple-auth-component.git#0.8.0-beta.1
Installed browser packages via Bower.
installing
The `ember generate` command requires an entity name to be specified. For more details, use `ember help`.

**Comment by hollow** [comment]
see https://github.com/Panman8201/ember-cli-bootswatch/issues/6 for a possible fix

**Comment by marcoow** [comment]
This is an Ember CLI bug (ember-cli/ember-cli#3846) that will be fixed in the next version probably. It actually installs Ember Simple Auth correctly regardless of the error message.
