### ISSUE TITLE
'POST http://localhost:4200/users/sign_in 404 (Not Found)' with Rails 5 version of Devise

### ISSUE THREAD

**Issue by FanaHOVA** [simplabs/ember-cli-simple-auth-devise#16]
I was trying around Rails 5 and had to use a modified version of Devise to make it work because of the new routes structure of Rails. The issue is that now every time I try to login I get a 404 error. 

    POST http://localhost:4200/users/sign_in 404 (Not Found)

My setup is identical to [this](http://johnmosesman.com/ember-simple-auth-tutorial-and-common-problems/) one. Just wanted to put this out here, I'll try and see if I can find a fix around this.

**Comment by marcoow** [comment]
When the request is going to the wrong URL (on in this case the wrong port I guess), you need to configure the [`serverTokenEndpoint`](http://ember-simple-auth.com/ember-simple-auth-devise-api-docs.html#SimpleAuth-Configuration-Devise-serverTokenEndpoint) correctly.
