### ISSUE TITLE
Ember 2.0 Support? Can't Find module

### ISSUE THREAD

**Issue by visoft** [simplabs/ember-cli-simple-auth-devise#17]
I'm trying to get this to work with the jj-abrams branch of ember-cli-simple-auth. I'm unable to get the site to load, it get the error:

Uncaught Error: Could not find module `simple-auth/utils/load-config` imported from `simple-auth-devise/configuration`

I'm guessing it's a problem between ember-cli-simple-auth-devise version 0.8.0 and the jj-abrams branch of ember-cli-simple-auth.

**Comment by visoft** [comment]
Nevermind, I figured out the new adapters were in the jj-abrams branch.

**Comment by fullofcaffeine** [comment]
Hey @visoft, could you elaborate? I'm having the exact same problem and I'm not sure what to look for. Thanks!

**Comment by visoft** [comment]
@fullofcaffeine - In the jj-abrams branch of ember-cli-simple-auth, you'll find the [devise authenticator](https://github.com/simplabs/ember-simple-auth/tree/jj-abrams/addon/authenticators/devise.js) and the [authorizer](https://github.com/simplabs/ember-simple-auth/blob/jj-abrams/addon/authorizers/devise.js). You don't need this ember-cli-simple-auth-devise if you're using the jj-abrams branch.
